apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
    - image: nekonex/employee
      jib:
        args:
          - "-DskipTests"
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml