apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nekonex-ingress
spec:
  rules:
    - host: nekonex-ingress.info
      http:
        paths:
          - path: /api/departments
            pathType: Prefix
            backend:
              service:
                name: department
                port:
                  number: 8080
          - path: /api/employees
            pathType: Prefix
            backend:
              service:
                name: employee
                port:
                  number: 8080
          - path: /v2
            pathType: Prefix
            backend:
              service:
                name: web2
                port:
                  number: 8080